routes/web.php
<?php

use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'ContatoController@index');

Route::group(['middleware'=>'auth', 'prefix'=>'contatos'], function() {
    Route::get('/', 'ContatoController@index');
    Route::get('/add', 'ContatoController@create');
    Route::post('/', 'ContatoController@store');
    Route::get('{id}', 'ContatoController@show');
    Route::get('/edit/{id}', 'ContatoController@edit');
    Route::put('{id}', 'ContatoController@update');
    Route::delete('{id}', 'ContatoController@destroy');
});

Route::get('/envio-email', function(){
    
    $user = new User;
    $user->name = Auth::user()->name;
    $user->Email = Auth::user()->email;
    
    //return new \App\Mail\mailAgenda($user);
    \App\Jobs\mailAgenda::dispatch($user->delay(now()->addSeconds('15')));
});

app/Contato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    protected $fillable = [
        'nome', 
        'telefone', 
        'email', 
        'data_nascimento', 
        'cep', 
        'logradouro', 
        'numero', 
        'complemento', 
        'bairro', 
        'localidade', 
        'uf', 
        'avatar', 
        'nota'
    ];

    // Accessor
    public function getAvatarImageAttribute($value) {
        return $this->avatar == null ? asset('images/null.png') : asset($this->avatar);
    }
    public function getAvatarFilenameAttribute($value) {
        return substr($this->avatar, 30, strlen($this->avatar));
    }
    public function getDataNascimentoAttribute($value) {
        return dateFormatDatabaseScreen($value, 'screen');
    }

    // Mutator
    public function setDataNascimentoAttribute($value) {
        $this->attributes['data_nascimento'] = dateFormatDatabaseScreen($value);
    }
    public function setAvatarAttribute($value) {
        $filename = substr(md5(rand(100000, 999999)),0,5) .'_'. $value->getClientOriginalName();
        $filepath = 'public/uploads/'.date('Y').'/'.date('m').'/';
        if ($value->isValid()) {
            $path = $value->storeAs($filepath, $filename);
        }
        $this->attributes['avatar'] = str_replace('public', 'storage', $filepath) . $filename;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Contato;
use App\Http\Requests\ContatoRequest;

class ContatoController extends Controller
{
      /**
     * ContatoController constructor.
     */
    public function __construct()
    {
        $this->middleware("auth");
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contatos = Contato::all()->sortBy('nome');
        return view('contato.index', compact('contatos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contato.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContatoRequest $request)
    {
        $contato = Contato::create($request->all());
        return redirect('contatos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contato = Contato::find($id);
        return view('contato.show', ['data' => $contato]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contato = Contato::find($id);
        return view('contato.edit', ['data' => $contato]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ContatoRequest $request, $id)
    {
        $contato = Contato::find($id);
        $contato->fill($request->all());
        $contato->update();
        return redirect('contatos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Contato::destroy($id);
        return redirect('contatos');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/contato/create.blade.php
@extends('layouts.app')

@section("js")
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Contato</div>
                <form action="{{ url('contatos') }}" method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="nome"><b>Nome completo</b></label>
                            <input type="text" required class="form-control{{$errors->has('nome') ? ' is-invalid':''}}" value="{{ old('nome') }}" id="nome" name="nome">
                            <div class="invalid-feedback">{{ $errors->first('nome') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="telefone"><b>Telefone</b></label>
                            <input type="text" required class="form-control{{$errors->has('telefone') ? ' is-invalid':''}}" value="{{ old('telefone') }}" id="telefone" name="telefone">
                            <div class="invalid-feedback">{{ $errors->first('telefone') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="email"><b>E-mail</b></label>
                            <input type="email" class="form-control{{$errors->has('email') ? ' is-invalid':''}}" value="{{ old('email') }}" id="email" name="email" placeholder="email@provedor.com.br">
                            <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="data_nascimento"><b>Data de nascimento</b></label>
                            <input type="text" class="form-control{{$errors->has('data_nascimento') ? ' is-invalid':''}}" id="data_nascimento" value="{{ old('data_nascimento') }}" name="data_nascimento" placeholder="00/00/0000">
                            <div class="invalid-feedback">{{ $errors->first('data_nascimento') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="cep"><b>CEP</b></label>
                            <input type="text" class="form-control{{$errors->has('cep') ? ' is-invalid':''}}" id="cep" value="{{ old('cep') }}" name="cep" placeholder="00000000">
                            <div class="invalid-feedback">{{ $errors->first('cep') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="logradouro"><b>Logradouro</b></label>
                            <input type="text" class="form-control{{$errors->has('logradouro') ? ' is-invalid':''}}" id="logradouro" value="{{ old('logradouro') }}" name="logradouro">
                            <div class="invalid-feedback">{{ $errors->first('logradouro') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="numero"><b>Número</b></label>
                            <input type="text" class="form-control{{$errors->has('numero') ? ' is-invalid':''}}" id="numero" value="{{ old('numero') }}" name="numero">
                            <div class="invalid-feedback">{{ $errors->first('numero') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="complemento"><b>Complemento</b></label>
                            <input type="text" class="form-control{{$errors->has('complemento') ? ' is-invalid':''}}" id="complemento" value="{{ old('complemento') }}" name="complemento">
                            <div class="invalid-feedback">{{ $errors->first('complemento') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="bairro"><b>Bairro</b></label>
                            <input type="text" class="form-control{{$errors->has('bairro') ? ' is-invalid':''}}" id="bairro" value="{{ old('bairro') }}" name="bairro">
                            <div class="invalid-feedback">{{ $errors->first('bairro') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="cidade"><b>Cidade</b></label>
                            <input type="text" class="form-control{{$errors->has('localidade') ? ' is-invalid':''}}" id="localidade" value="{{ old('localidade') }}" name="localidade">
                            <div class="invalid-feedback">{{ $errors->first('localidade') }}</div>
                        </div>

                        <div class="form-group">
                            <label for="uf"><b>UF</b></label>
                            <input type="text" class="form-control{{$errors->has('uf') ? ' is-invalid':''}}" id="uf" value="{{ old('uf') }}" name="uf">
                            <div class="invalid-feedback">{{ $errors->first('uf') }}</div>
                        </div>
                        
                        <div class="form-group">
                            <label for="avatar"><b>Avatar</b></label>
                            <input type="file" class="form-control-file{{$errors->has('avatar') ? ' is-invalid':''}}" id="avatar" name="avatar" accept=".jpg, .jpeg, .png .gif">
                            <div class="invalid-feedback" style="display:inherit">{{ $errors->first('avatar') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="nota"><b>Nota</b></label>
                            <textarea class="form-control" id="nota" name="nota" rows="5">{{ old('nota') }}</textarea>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <a href="#" onclick="history.back()" class="btn btn-secondary">Voltar</a>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@section("script")
    <script type="text/javascript" > 
    $(document).ready(function() {
        $("#cep").focusout(function(){
            $.ajax({
                url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/unicode/',
                dataType: 'json',
                success: function(resposta){
                    
                    $("#logradouro").val(resposta.logradouro);
                    $("#bairro").val(resposta.bairro);
                    $("#localidade").val(resposta.localidade);
                    $("#uf").val(resposta.uf);
                    
                    $("#numero").focus();
                }
            });
        });
    });
</script>
@endsection

resources/views/contato/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><u>EDITAR</u></div>
                <form action="{{ url('contatos/'.$data->id) }}" method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        @method('PUT')

                        @csrf

                        <div class="form-group">
                            <label for="nome"><b>Nome completo</b></label>
                            <input type="text" required class="form-control{{$errors->has('nome') ? ' is-invalid':''}}" value="{{ old('nome',$data->nome) }}" id="nome" name="nome">
                            <div class="invalid-feedback">{{ $errors->first('nome') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="telefone"><b>Telefone</b></label>
                            <input type="text" required class="form-control{{$errors->has('telefone') ? ' is-invalid':''}}" value="{{ old('telefone',$data->telefone) }}" id="telefone" name="telefone">
                            <div class="invalid-feedback">{{ $errors->first('telefone') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="email"><b>E-mail</b></label>
                            <input type="email" class="form-control{{$errors->has('email') ? ' is-invalid':''}}" value="{{ old('email',$data->email) }}" id="email" name="email" placeholder="email@provedor.com.br">
                            <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="data_nascimento"><b>Data de nascimento</b></label>
                            <input type="text" class="form-control{{$errors->has('data_nascimento') ? ' is-invalid':''}}" id="data_nascimento" value="{{ old('data_nascimento',$data->data_nascimento) }}" name="data_nascimento" >
                            <div class="invalid-feedback">{{ $errors->first('data_nascimento') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="cep"><b>CEP</b></label>
                            <input type="text" class="form-control{{$errors->has('cep') ? ' is-invalid':''}}" id="cep" value="{{ old('cep',$data->cep) }}" name="cep" placeholder="00000000">
                            <div class="invalid-feedback">{{ $errors->first('cep') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="logradouro"><b>Logradouro</b></label>
                            <input type="text" class="form-control{{$errors->has('logradouro') ? ' is-invalid':''}}" id="logradouro" value="{{ old('logradouro',$data->logradouro) }}" name="logradouro">
                            <div class="invalid-feedback">{{ $errors->first('logradouro') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="numero"><b>Número</b></label>
                            <input type="text" class="form-control{{$errors->has('numero') ? ' is-invalid':''}}" id="numero" value="{{ old('numero',$data->numero) }}" name="numero">
                            <div class="invalid-feedback">{{ $errors->first('numero') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="complemento"><b>Complemento</b></label>
                            <input type="text" class="form-control{{$errors->has('complemento') ? ' is-invalid':''}}" id="complemento" value="{{ old('complemento',$data->complemento) }}" name="complemento">
                            <div class="invalid-feedback">{{ $errors->first('complemento') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="bairro"><b>Bairro</b></label>
                            <input type="text" class="form-control{{$errors->has('bairro') ? ' is-invalid':''}}" id="bairro" value="{{ old('bairro',$data->bairro) }}" name="bairro">
                            <div class="invalid-feedback">{{ $errors->first('bairro') }}</div>
                        </div>
                        <div class="form-group">
                            <label for="cidade"><b>Cidade</b></label>
                            <input type="text" class="form-control{{$errors->has('localidade') ? ' is-invalid':''}}" id="localidade" value="{{ old('localidade',$data->localidade) }}" name="localidade">
                            <div class="invalid-feedback">{{ $errors->first('localidade') }}</div>
                        </div>

                        <div class="form-group">
                            <label for="uf"><b>UF</b></label>
                            <input type="text" class="form-control{{$errors->has('uf') ? ' is-invalid':''}}" id="uf" value="{{ old('uf',$data->uf) }}" name="uf">
                            <div class="invalid-feedback">{{ $errors->first('uf') }}</div>
                        </div>
                        
                        
                        <div class="form-group">
                            <label for="avatar"><b>Avatar</b></label>
                            <input type="file" class="form-control-file{{$errors->has('avatar') ? ' is-invalid':''}}" id="avatar" name="avatar" accept=".jpg, .jpeg, .png .gif">
                            <div class="invalid-feedback" style="display:inherit">{{ $errors->first('avatar') }}</div>
                            <!-- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file -->
                        </div>
                        <div class="form-group">
                            <label for="nota"><b>Nota</b></label>
                            <textarea class="form-control" id="nota" name="nota" rows="5">{{ old('nota',$data->nota) }}</textarea>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <a href="#" onclick="history.back()" class="btn btn-secondary">Voltar</a>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/contato/index.blade.php
@extends('layouts.app')

@section('stylecss')
<style media="screen">
    .img-avatar-xs {
        width: 30px;
        height: 30px;
        border: 1px solid #c0c0c0;
        border-radius: 5px;
    }
    .a-line {
        line-height: 30px;
    }
</style>

@endsection

@section('content')

<div class="container">
    <div class="card">
        <div class="card-header">
             AGENDA 
            <a href="{{ url('contatos/add') }}" class="btn btn-primary btn-sm float-right">Adicionar contato</a>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive border-0">
                <table class="table table-striped" style="margin-bottom: inherit">
                    <tbody>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Nome</th>
                            <th class="text-center">Telefone</th>
                            <th class="text-center">E-mail</th>
                        </tr>
                        @foreach ($contatos as $contato)
                        <tr>
                            <td class="text-center">
                                <a  href="{{ url('contatos/'.$contato->id) }}">
                                    <img src="{{ $contato->avatar_image }}" class="img-avatar-xs">
                                </a>
                            </td>
                            <td class="text-center" class="d-none d-md-table-cell"><a class='a-line' href="{{ url('contatos/'.$contato->id) }}">{{ $contato->nome }}</a></td>
                            <td class="text-center" class="d-none d-md-table-cell"><a class='a-line'  href="{{ url('contatos/'.$contato->id) }}">{{ $contato->telefone }}</a></td>
                            <td class="text-center" class="d-none d-md-table-cell"><a class='a-line' href="{{ url('contatos/'.$contato->id) }}">{{ $contato->email }}</a></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/contato/show.blade.php
@extends('layouts.app')

@section('stylecss')
<style>
.form-control-static {
    font-weight: bold;
}
.img-avatar {
    max-width: 100%;
    border: 1px solid #c0c0c0;
    border-radius: 5px;
    margin-bottom: 15px;
}
</style>
@endsection

@section('script')
<script type="text/javascript">
function validate_delete() {
    return confirm('Excluir o registro atual? Essa ação não pode ser desfeita.');
}
</script>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><U>CONTATO</u></div>
                <form action="{{ url('contatos/'.$data->id) }}" method="post" onsubmit="return validate_delete()">
                    <div class="card-body">
                        @method('DELETE')

                        {{ csrf_field() }}

                        <div class="row">
                                <div class="col-sm-4">
                                    <img src="{{ $data->avatar_image }}" class="responsive">
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="nome"><u><b>Nome:</b></u></label>
                                        <p class="form-control-static">{{ $data->nome }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="telefone"><u><b>Telefone:</b></u></label>
                                        <p class="form-control-static">{{ $data->telefone }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="email"><u><b>E-mail:</b></u></label>
                                        <p class="form-control-static">{{ $data->email }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="data_nascimento"><u><b>Data de Nascimento:</b></u></label>
                                        <p class="form-control-static">{{ $data->data_nascimento }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="cep"><u><b>CEP:</b></u></label>
                                        <p class="form-control-static">{{ $data->cep }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="logradouro"><u><b>Logradouro:</b></u></label>
                                        <p class="form-control-static">{{ $data->logradouro }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="numero"><u><b>Número:</b></u></label>
                                        <p class="form-control-static">{{ $data->numero }}</p>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="complemento"><u><b>Complemento:</b></u></label>
                                        <p class="form-control-static">{{ $data->complemento }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="bairro"><u><b>Bairro:</b></u></label>
                                        <p class="form-control-static">{{ $data->bairro }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="localidade"><u><b>Cidade:</b></u></label>
                                        <p class="form-control-static">{{ $data->localidade }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="uf"><u><b>UF:</b></u></label>
                                        <p class="form-control-static">{{ $data->uf }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="nota"><u><b>Nota:</b></u></label>
                                        <p class="form-control-static">{{ $data->nota }}</p>
                                    </div>
                                </div>
                                

                            </div><!-- /.row -->
                        </div>
                    <div class="card-footer text-right">
                        <a href="#" onclick="history.back()" class="btn btn-secondary">Voltar</a>
                        <button type="submit" class="btn btn-danger">Excluir</button>
                        <a href="{{ url('contatos/edit/'.$data->id) }}" class="btn btn-primary">Editar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style>
        .img-resposive {
            width: 20%;
            height: auto
        }
    </style>

    @yield('stylecss')
</head>
<body>
    @yield("js")
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a href="{{ url('contatos/') }}">
                    <img class="img-resposive" src="https://app.vexpenses.com/assets/images/logo-horizontal.png" alt="Pagina Inicial" title="Pagina Inicial" >
                </a>
                

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto" style="font-size:100%">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item" >
                                <a class="nav-link"  href="{{ route('login') }}">{{ __('Login') }} </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield("script")
</body>
</html>